# ─────────────────────────────────────────────
# EXPLORES — update for your migration
# ─────────────────────────────────────────────
OLD_EXPLORE  = ["product_facts"]
NEW_MODEL    = "super_big_facts"
NEW_EXPLORE  = "product_usage_org_proj"
NEW_EXPLORE_2 = "product_usage_sdk"

# ─────────────────────────────────────────────
# VIEWS joined into NEW_EXPLORE
# Any field from a view NOT in this list will be flagged by --validate
# Add views here as you confirm they exist in product_usage_org_proj
# ─────────────────────────────────────────────
JOINED_VIEWS_IN_NEW_EXPLORE = {
    "accounts_billingmetricusage_on_org",
    "daily_arr_by_category",
    "daily_arr_combined",
    "daily_financial_data_billing_category",
    "daily_financial_data_billing_category_struct",
    "engagement_score",
    "issues_org_type",
    "organizations",
    "organizations_age_tracking",
    "organizations_analytics_summary",
    "organizations_autofix_usage",
    "organizations_cron_monitoring",
    "organizations_dashboards",
    "organizations_data_outcomes",
    "organizations_emerge",
    "organizations_events",
    "organizations_feature_adoption_dates",
    "organizations_feature_flags",
    "organizations_feedback_received",
    "organizations_integrations",
    "organizations_issues",
    "organizations_promocode_usage",
    "organizations_seer",
    "organizations_sso_configuration",
    "organizations_uptime_monitoring",
    "product_facts_v2_base",
    "projects_analytics_summary",
    "projects_base_table",
    "projects_data_outcomes",
    "projects_emerge",
    "projects_metric_alerts",
    "projects_uptime_monitoring",
    "sdk_base_events",
    "sdk_org_events",
    "subscriptions_v3",
    "users_seer",
}

# ─────────────────────────────────────────────
# FIELD MAPS — keyed by (old_explore, new_explore)
# Fields from joined views that haven't changed don't need to be listed here
# ─────────────────────────────────────────────
FIELD_MAPS = {
("product_facts", "product_usage_org_proj"): {
    "product_facts.organizations_count":        "product_facts_v2_base.count",
    "product_facts.active_organizations_count": "organizations.active_organizations_count",
    "product_facts.dt_date":                    "product_facts_v2_base.dt_date",
    "product_facts.dt_month":                   "product_facts_v2_base.dt_month",
    "product_facts.is_last_day_of_month":       "product_facts_v2_base.is_last_day_of_month",
    "product_facts.is_last_day_of_week":        "product_facts_v2_base.is_last_day_of_week",
    "product_facts.org_age":                    "organizations_age_tracking.org_age",
    "product_facts.org_active":                 "organizations.is_active",
    "product_facts.organization_slug":          "organizations.slug",
    "product_facts.organization_id":            "product_facts_v2_base.organization_id",
    "product_facts.sum_org_active_users_28d":   "organizations.active_users_28d",
    "product_facts.sum_active_projects":        "organizations_data_outcomes.org_active_projects",
    "product_facts.sum_spans_accepted":         "projects_data_outcomes.daily_spans_accepted",
    "product_facts.sum_replays_accepted":       "projects_data_outcomes.replays_accepted",
    "product_facts.sum_errors_accepted":        "projects_data_outcomes.errors_accepted",
    # uptime monitor field renamed in new explore
    "organization_uptime_summary.org_dt_total_active_monitors": "organizations.org_dt_total_active_monitors",
    # logs field renamed in new explore
    "data_by_project.proj_logs_accepted":                       "projects_data_outcomes.logs_items_accepted",
    # metrics field mapped
    "data_by_project.proj_trace_metric_items_accepted": "projects_data_outcomes.trace_metric_items_accepted",
    # TODO — find new field name for this before migrating dashboards that use it:
    # "project_uptime_details.total_active_monitors":           "???",
    # === additional mappings ===
    "product_facts.dt_week": "product_facts_v2_base.dt_week",
    "new_seer_orgs.estimated_seats": "organizations_seer.estimated_seats",
    "product_facts_org_seer_user_rollup.billable_seats_28d": "users_seer.billable_seats_28d",
    "org_feedback_received.total_comments": "organizations_feedback_received.total_comments",
    "org_feedback_received.total_fixes_applied": "organizations_feedback_received.total_fixes_applied",
    "org_feedback_received.total_fixes_rejected": "organizations_feedback_received.total_fixes_rejected",
    "org_feedback_received.total_downvotes": "organizations_feedback_received.total_downvotes",
    "org_feedback_received.total_upvotes": "organizations_feedback_received.total_upvotes",
    "org_feedback_received.total_hearts": "organizations_feedback_received.total_hearts",
    "subscriptions_v3.total_churn_arr": "daily_arr_changes_org.sum_total_churn_arr",
    "product_facts.orgs_issue_details_viewed_has_root_cause_true": "organizations_seer.orgs_issue_details_viewed_has_root_cause_true",
    "product_facts.orgs_found_solution": "organizations_seer.orgs_found_solution",
    "product_facts.orgs_autofix_pr_merged": "organizations_autofix_usage.sum_autofix_merged_prs",
    "new_seer_orgs.is_new_seer_org": "organizations_seer.is_new_seer_org",
    "new_seer_orgs.seer_enabled_week": "organizations_seer.seer_enabled_week",
    "new_seer_orgs.total_invoiced_seats": "organizations_seer.total_invoiced_seats",
    "new_seer_orgs.seer_churn_date": "organizations_seer.seer_churn_date",
    "new_seer_orgs.seer_enabled_date": "organizations_seer.seer_enabled_date",
    "new_seer_orgs.seats_at_churn": "organizations_seer.seats_at_churn",
    "product_facts_org_seer.total_events_sum": "organizations_seer.total_events_sum",
    "product_facts_org_seer.total_unique_prs_sum": "organizations_seer.total_unique_prs_sum",
    "product_facts_org_seer.total_unique_repos_sum": "organizations_seer.total_unique_repos_sum",
    "new_seer_orgs.seer_enabled_month": "organizations_seer.seer_enabled_month",
    "org_feedback_received.prs_with_feedback": "organizations_feedback_received.prs_with_feedback",
    "product_facts_org_seer.total_unique_repos": "organizations_seer.total_unique_repos",
    "product_facts.seer_cohort": "organizations_seer.seer_cohort",
    "product_facts.seer_filter_mode": "organizations_seer.seer_filter_mode",
    "product_facts.seer_segment_match": "organizations_seer.seer_segment_match",
    "product_facts_org_seer_user_rollup.is_billable_any_seat_28d": "users_seer.is_billable_any_seat_28d",
    "product_facts.seer_billable_seats_28d": "organizations_seer.seer_billable_seats_28d",
    "seer_usage_cost.total_dollar_cost": "organizations_seer.total_dollar_cost",
    "seer_usage_cost.step": "organizations_seer.step",
    "seer_usage_cost.feature": "organizations_seer.feature",
    "seer_pr_events.distinct_prs": "organizations_seer.distinct_prs",
    "product_facts.trace_metric_items_accepted_28d": "organizations_data_outcomes.trace_metric_items_accepted_28d",
    "metric_type_events.metric_items": "projects_data_outcomes.metrics_accepted",
    "data_by_sdk.trace_metric_size_bytes_28d": "sdk_base_events.trace_metric_size_bytes_28d_proj_sdk",
    "data_by_sdkversion.trace_metric_items": "sdk_base_events.trace_metric_items",
    "data_by_sdk.trace_metric_items_28d": "sdk_base_events.trace_metric_items_28d_proj_sdk",
    "data_by_sdk.sdk_name": "sdk_base_events.sdk_name",
    "data_by_sdkversion.trace_metric_size_bytes": "sdk_base_events.trace_metric_size_bytes",
    "data_by_sdkversion.median_metric_size_bytes": "sdk_base_events.median_trace_metric_size_bytes",
    "metric_type_events.median_attributes": "projects_data_outcomes.median_attributes",
    "product_facts.org_ea_flag": "organizations_analytics_summary.org_ea_flag",
    "product_facts.is_last_day_of_fiscal_quarter": "product_facts_v2_base.is_last_day_of_fiscal_quarter",
    "product_facts.dt_fiscal_quarter": "product_facts_v2_base.dt_fiscal_quarter",
    "product_facts_promocodeclaimant.date_added_month": "organizations_promocode_usage__promo_code_struct.date_added_month",
    "product_facts_promocodeclaimant.date_added_date": "organizations_promocode_usage__promo_code_struct.date_added_date",
    "product_facts_promocodeclaimant.promocode": "organizations_promocode_usage__promo_code_struct.promocode",
    "product_facts_promocodeclaimant.date_added_week": "organizations_promocode_usage__promo_code_struct.date_added_week",
    "product_facts_promocodeclaimant.promocode_id": "organizations_promocode_usage__promo_code_struct.promocode_id",
    "subscriptions_v3.total_new_arr": "daily_arr_changes_org.sum_total_new_arr",
    "subscriptions_v3.total_expansion_arr": "daily_arr_changes_org.sum_total_expansion_arr",
    "product_facts.replays_accepted_28d": "projects_data_outcomes.replays_accepted_28d",
    "product_facts.errors_accepted_28d": "projects_data_outcomes.errors_accepted_28d",
    "product_facts.transactions_accepted_28d": "projects_data_outcomes.transactions_accepted_28d",
    "product_facts.replays_utilization_rate": "projects_data_outcomes.replays_utilization_rate",
    "product_facts.spans_utilization_rate": "projects_data_outcomes.spans_utilization_rate",
    "product_facts.transactions_utilization_rate": "projects_data_outcomes.transactions_utilization_rate",
    "product_facts.errors_utilization_rate": "projects_data_outcomes.errors_utilization_rate",
    "product_facts.logs_accepted_28d": "projects_data_outcomes.logs_bytes_accepted_28d",
    "product_facts.org_active_users_28d": "organizations_active_users.org_active_users_28d",
    "product_facts.spans_accepted_28d": "organizations_data_outcomes.spans_accepted_28d",
    "billing_model.sum_total_churn_arr": "daily_arr_changes_org.sum_total_churn_arr",
    "product_facts_emerge.size_builds_28d": "organizations_emerge.size_builds_28d",
    "product_facts_emerge.size_builds_total": "projects_emerge.size_builds_total",
    "emerge_project.size_builds_total": "projects_emerge.size_builds_total",
    "emerge_project.size_builds_28d": "projects_emerge.size_builds_28d",
    "data_by_project.project_platform": "sentry_project.platform",
    "product_facts.sum_org_users_total": "organizations_active_users.org_users_total",
    "product_facts_emerge.distribution_builds_28d": "organizations_emerge.distribution_builds_28d",
    "product_facts_emerge.distribution_builds_total": "organizations_emerge.distribution_builds_total",
    "product_facts_emerge.distribution_installs_total": "organizations_emerge.distribution_installs_total",
    "product_facts_emerge.distribution_installs_28d": "projects_emerge.distribution_installs_28d",
    "emerge_first_adoption_dates.first_size_analysis_date_week": "organizations_feature_adoption_dates.first_size_analysis_date",
    "emerge_first_adoption_dates.first_size_analysis_date_date": "organizations_feature_adoption_dates.first_size_analysis_date",
    "emerge_first_adoption_dates.first_distribution_build_date_week": "organizations_feature_adoption_dates.first_distribution_builds_week",
    "emerge_first_adoption_dates.first_distribution_build_date_date": "organizations_feature_adoption_dates.first_distribution_builds_date",
    "product_facts.crons_active_monitor_1d": "organizations_cron_monitoring.crons_active_monitor_1d",
    "product_facts_events.sdk_family": "organizations_events.sdk_family",
    "product_facts.performance_units_accepted": "projects_data_outcomes.performance_units_accepted",
    "product_facts_events.event_type": "organizations_events.event_type",
    "accounts_billingmetricusage_on_org.outcome_readable": "accounts_billingmetricusage_on_org.outcome_readable",
    "organization_uptime_summary.has_active_crons_and_manual_uptime_alerts": "organizations_uptime_monitoring.has_active_crons_and_manual_uptime_alerts",
    "data_by_sdkversion.total_profile_duration_continuous": "sdk_base_events.profile_duration_backend",
    "data_by_sdkversion.profile_duration_frontend": "sdk_base_events.profile_duration_frontend",
    "data_by_sdkversion.profile_duration_backend": "sdk_base_events.profile_duration_backend",
    "product_facts.combined_integration_features": "organizations_integrations.all_integration_features_string",
    "data_by_project.project_name": "sentry_projects.name",
    "data_by_project.project_id": "product_facts_v2_base.project_id",
    "data_by_project.project_count": "projects_data_outcomes.project_count",
    "data_by_project.proj_errors_accepted": "projects_data_outcomes.errors_accepted",
    "data_by_project.has_environments_current_enabled": "projects_configuration.has_environments_current_flag",
    "data_by_project.primary_sdk": "projects_base_table.primary_sdk",
    "product_facts.org_active_backend": "organizations_feature_flags.org_active_backend",
    "product_facts_events.number_of_events_sum": "organizations_events.number_of_events_sum",
    "billing_model_billing_category.sum_contraction_arr": "daily_arr_changes_category.sum_total_contraction_arr",
    "billing_model_billing_category.sum_reactivation_arr": "daily_arr_changes_category.sum_total_reactivation_arr",
    "daily_financial_data_billing_category_struct.change_in_ondemand_arr": "daily_arr_changes_category.ondemand_change_arr",
    "billing_model_billing_category.sum_churn_arr": "daily_arr_changes_category.sum_total_churn_arr",
    "billing_model_billing_category.sum_new_arr": "daily_arr_changes_category.sum_total_new_arr",
    "billing_model.billing_model": "daily_arr_by_category.billing_model",
    "billing_model_billing_category.sum_expansion_arr": "daily_arr_changes_category.sum_total_expansion_arr",
    "product_facts.first_continuous_profile_date_date": "organizations_feature_adoption_dates.first_continuous_profile_date",
    "product_facts.profile_duration_accepted_28d": "organizations_data_outcomes.profile_duration_accepted_28d",
    "product_facts.frontend_profile_duration_accepted_28d": "projects_data_outcomes.frontend_profile_duration_accepted_28d",
    "product_facts.first_ui_profile_date_date": "organizations_feature_adoption_dates.first_ui_profile_date_date",
    "product_facts.front_end_profile_duration_accepted_sum": "projects_data_outcomes.frontend_profile_duration_accepted",
    "product_facts.profile_duration_accepted_sum": "projects_data_outcomes.profile_duration_accepted",
    "product_facts.total_profile_duration_accepted_sum": "organizations_data_outcomes.profile_duration_accepted",
    "data_by_sdk.pduration_frontend_28d_sdk_family": "sdk_base_events.pduration_frontend_28d_proj_sdkfamily",
    "data_by_sdk.sdk_family": "sdk_map_new.language_family",
    "data_by_sdk.pduration_backend_28d_sdk_family": "sdk_base_events.pduration_backend_28d_proj_sdkfamily",
    "product_facts.total_profile_duration_accepted_28d": "projects_data_outcomes.profile_duration_accepted_28d",
    "product_facts.org_active_frontend": "sdk_map_new.framework_frontend",
    "product_facts.sum_indexed_spans_accepted": "projects_data_outcomes.indexed_spans_accepted",
    "product_facts_events.sdk_name": "organizations_events.sdk_name",
    "data_by_sdkversion.number_of_events": "sdk_base_events.events",
    "product_facts.indexed_spans_accepted_28d": "projects_data_outcomes.indexed_spans_accepted_28d",
    "product_facts.seer_issue_scans_accepted_28d": "organizations_data_outcomes.seer_issue_scans_accepted_28d",
    "product_facts.seer_issue_fixes_accepted_28d": "organizations_data_outcomes.seer_issue_fixes_accepted_28d",
    "product_facts.logs_count_28d": "projects_data_outcomes.logs_items_accepted_28d",
    "per_product_trials.trial_type": "organizations_per_product_trials.trial_type",
    "product_facts.daily_new_issues_28d_org": "organizations_issues.daily_new_issues_28d_org",
    "product_facts.error_issue_views_28day_agg": "organizations_analytics_specific.error_issue_views_28d_org",
    "product_facts.daily_resolved_issues_28d_org": "projects_issues.daily_resolved_issues_28d_proj",
    "product_facts_events.events_28d": "organizations_data_outcomes.events_accepted_28d",
    "product_facts.org_team_count": "organizations_analytics_summary.org_team_count",
    "product_facts.daily_ignored_issues_28d_org": "projects_issues.daily_ignored_issues_28d_proj",
    "product_facts.profile_issue_views_28day_agg": "projects_analytics_specific.profile_issue_views_28d_proj",
    "product_facts.performance_issue_views_28day_agg": "projects_analytics_specific.performance_issue_views_28d_proj",
    "health_flags.active_flag": "organizations_analytics_summary.active_flag",
    "health_flags.engagement_flag": "organizations_analytics_summary.engagement_flag",
    "product_facts.generated_issue_alerts_28d": "projects_analytics_specific.generated_issue_alerts_28d_proj",
    "product_facts.generated_metric_alerts_28d": "projects_analytics_specific.generated_metric_alerts_28d_proj",
    "product_facts.generated_any_alerts_28d": "projects_analytics_specific.generated_total_alerts_28d_proj",
    "product_facts.sum_logs_accepted": "projects_data_outcomes.logs_bytes_accepted",
    "data_by_sdkversion.log_size_bytes": "sdk_base_events.log_size_bytes",
    "data_by_sdk.log_size_bytes_28d": "sdk_base_events.log_size_bytes_28d_proj_sdk",
    "data_by_sdkversion.median_log_size_bytes": "sdk_base_events.median_log_size_bytes",
    "data_by_sdkversion.logs_origin": "sdk_base_events.logs_origin",
    "product_facts.first_logs_date_date": "organizations_feature_adoption_dates.first_logs_date_date",
    "product_facts.first_logs_date_month": "organizations_feature_adoption_dates.first_logs_date_month",
    "data_by_sdk.events_28d_proj_sdkfamily": "sdk_base_events.events_28d_proj_sdkfamily",
    "data_by_sdk.log_size_bytes_28d_proj_sdkfamily": "sdk_base_events.log_size_bytes_28d_proj_sdkfamily",
    "trial_view.trial_start_month": "organizations_trial_view.trial_start_month",
    "top_projects_by_org.is_top_3_project": "projects_base_table.is_top_3_project",
    "data_by_project.events_accepted_28d": "projects_data_outcomes.events_accepted_28d",
    "data_by_project.proj_seer_issue_scans_accepted_28d": "projects_data_outcomes.seer_issue_scans_accepted_28d",
    "data_by_project.all_spans_28d": "projects_data_outcomes.all_spans_28d",
    "data_by_project.proj_seer_issue_fixes_accepted_28d": "projects_data_outcomes.seer_issue_fixes_accepted_28d",
    "data_by_project.all_transactions_28d": "projects_data_outcomes.all_transactions_28d",
    "data_by_project.replays_accepted_28d": "projects_data_outcomes.replays_accepted_28d",
    "data_by_project.logs_count_28d": "projects_data_outcomes.logs_items_accepted_28d",
    "product_facts.github_integration": "organizations_integrations.github_integration",
    "per_product_trials.product_trial_start_date": "organizations_per_product_trials.product_trial_start_date",
    "project_uptime_details.auto_detected_monitors": "projects_uptime_monitoring.auto_detected_monitors",
    "project_uptime_details.onboarding_monitors": "projects_uptime_monitoring.sum_onboarding_monitors",
    "project_uptime_details.manually_created_monitors": "projects_uptime_monitoring.manually_created_monitors",
    "data_by_sdk.mobile_replays_28d_proj_sdkfamily": "sdk_base_events.mobile_replays_28d_proj_sdkfamily",
    "data_by_sdk.total_pduration__28d_sdk_family": "sdk_base_events.total_pduration__28d_sdk_family",
    "data_by_sdk.replays_28d_proj_sdkfamily": "sdk_base_events.replays_28d_proj_sdkfamily",
    "data_by_sdk.total_accepted_replay_count": "sdk_base_events.replays_28d_proj_sdk",
    "data_by_sdk.number_of_mobile_replays_28d": "sdk_base_events.mobile_replays_28d_proj_sdk",
    "data_by_sdk.Total_replays_28d": "sdk_base_events.replays_28d_proj_sdk",
    "trial_view.next_invoice_channel": "organizations_trial_view.next_invoice_channel",
    "product_facts.dt_day_of_week": "product_facts_v2_base.dt_day_of_week",
    "trial_view.next_edition": "organizations_trial_view.next_edition",
    "product_facts.org_users_total": "organizations_active_users.org_users_total",
    "product_facts.organization_name": "organizations_analytics_summary.organization_name",
    "product_facts.crons_monitors_28d": "organizations_cron_monitoring.crons_monitors_28d",
    "product_facts_events.active_sdk": "organizations_events.active_sdk",
    "trial_view.trial_start_date": "organizations_trial_view.trial_start_date",
    "billing_model.sum_total_new_arr": "daily_arr_changes_org.sum_total_new_arr",
    "billing_model.sum_total_expansion_arr": "daily_arr_changes_org.sum_total_expansion_arr",
    "product_facts.crons_active_monitor_28d": "organizations_cron_monitoring.crons_active_monitor_28d",
    "product_facts.crons_checkins_daily": "organizations_cron_monitoring.crons_checkins_daily",
    "data_by_project.project_first_event_date_date": "sentry_projects.first_event_date",
    "data_by_project.errors_accepted_28d": "projects_data_outcomes.errors_accepted_28d",
    "data_by_project.transactions_accepted_28d": "projects_data_outcomes.transactions_accepted_28d",
    "data_by_project.proj_seer_issue_fixes_accepted": "projects_data_outcomes.seer_issue_fixes_accepted",
    "product_facts_integrations_array.individual_integration_features": "organizations_integrations.individual_integration_features",
    "data_by_project.proj_seer_issue_scans_accepted": "projects_data_outcomes.seer_issue_scans_accepted",
    "product_facts_autofix_llm.autofix_runs_sum": "organizations_autofix_usage.autofix_runs_sum",
    "data_by_sdkversion.errors": "sdk_base_events.errors",
    "data_by_project.proj_replays_accepted": "projects_data_outcomes.replays_accepted",
    "data_by_sdkversion.sdk_version_replays_support_proj": "sdk_mapping_minversion.replay_support",
    "sdk_mapping_minversion_project.transaction_support": "sdk_org_events.transaction_support",
    "data_by_sdkversion.sdk_version_crons_support_proj": "sdk_mapping_minversion.crons_support",
    "sdk_mapping_minversion_project.profile_support": "sdk_org_events.profile_support",
    "data_by_sdkversion.uses_latest_sdk_version": "sdk_base_events.uses_latest_sdk_version",
    "data_by_sdkversion.profiles": "sdk_base_events.profiles",
    "data_by_sdkversion.sdk_version": "sdk_base_events.sdk_version",
    "data_by_sdkversion.sdk_version_profiles_support_proj": "sdk_mapping_minversion.profile_support",
    "sdk_mapping_minversion_project.crons_support": "sdk_org_events.crons_support",
    "data_by_sdk.sdk_integrations_string": "sdk_base_events.sdk_integrations_string",
    "data_by_sdkversion.transactions": "sdk_base_events.transactions",
    "sdk_mapping_minversion_project.replay_support": "sdk_org_events.replay_support",
    "data_by_project.proj_spans_accepted": "projects_data_outcomes.daily_spans_accepted",
    "data_by_sdkversion.sdk_version_transactions_support_proj": "sdk_mapping_minversion.transaction_support",
    "data_by_project.profiles_accepted_28d": "projects_data_outcomes.profiles_accepted_28d",
    "data_by_project.attachments_accepted_28d": "projects_data_outcomes.attachments_accepted_28d",
    "data_by_project.spike_protection_disabled": "projects_configuration.spike_protection_disabled_flag",
    "data_by_project.regression_issue_alerts_count": "projects_alert_rules.count_of_alerts_for_regression",
    "data_by_project.sdk_integrations_enabled": "projects_events.sdk_integrations_flag",
    "data_by_project.new_issue_alerts_count": "projects_alert_rules.count_of_alerts_for_new_issues",
    "data_by_project.single_event_issue_percent_28d_proj": "projects_base_table.single_event_issue_percent_28d_proj",
    "data_by_project.messaging_integration_issue_alerts_count": "projects_alert_rules.count_of_messaging_integrations",
    "data_by_project.proj_team_member_count": "projects_team_assignments.team_members_count",
    "sdk_integrations_array.individual_sdk_integrations": "sdk_org_events.individual_sdk_integrations",
    "data_by_sdk.sessions_crash_free_sum": "sdk_base_events.sessions_crash_free_sum",
    "data_by_project.environment_based_metric_alerts_count": "projects_metric_alerts.environment_based_alert_rules_count",
    "data_by_project.client_side_sampling_used": "projects_data_outcomes.client_side_sampling_used",
    "data_by_project.server_side_filters_used": "projects_configuration.server_side_filters_used",
    "data_by_project.error_spike_metric_alerts_count": "projects_metric_alerts.error_spike_metric_alerts_count",
    "data_by_project.client_side_filters_used": "projects_data_outcomes.client_side_filters_used",
    "data_by_project.error_count_issue_alerts_count": "projects_alert_rules.count_of_alerts_for_issue_based_event_count",
    "data_by_project.transactional_data_metric_alerts_count": "projects_metric_alerts.transaction_based_alerts_count",
    "data_by_project.custom_tags_issue_alerts_count": "projects_alert_rules.count_of_alert_rules_with_custom_tags",
    "data_by_project.team_notification_issue_alert_count": "projects_alert_rules.count_of_alert_rules_notifying_team",
    "product_facts.sso_provider": "organizations_sso_configuration.provider",
    "product_facts.sso_users_28d": "organizations_sso_configuration.num_users_last_28days_from_snapshot",
    "product_facts.external_ticket_integration_flag": "organizations_integrations.external_ticket_integration_flag",
    "product_facts.sso_status": "organizations_sso_configuration.sso_status",
    "data_by_project.errors_over_quota_quarter_count": "projects_configuration.errors_over_quota_quarter_count",
    "data_by_project.transactions_over_quota_quarter_count": "projects_configuration.transactions_over_quota_quarter_count",
    "data_by_project.spend_allocation_enabled_flag": "projects_configuration.spend_allocation_enabled_flag",
    "data_by_project.replays_over_quota_quarter_count": "projects_configuration.replays_over_quota_quarter_count",
    "data_by_project.create_jira_ticket_issue_alert_count": "projects_alert_rules.count_of_alert_rules_to_create_ticket",
    "data_by_project.daily_resolved_issues_28d_proj": "projects_issues.daily_resolved_issues_28d_proj",
    "data_by_project.codemapping_enabled": "projects_configuration.codemapping_enabled_flag",
    "data_by_project.daily_new_issues_28d_proj": "projects_issues.daily_new_issues_28d_proj",
    "data_by_project.releases_created_through_cli": "projects_releases.releases_created_through_cli",
    "data_by_project.releases_having_commits_associated": "projects_releases.releases_having_commits_associated",
    "data_by_project.ownership_rules": "projects_configuration.number_of_ownership_rules",
    "data_by_project.daily_ignored_issues_28d_proj": "projects_issues.daily_ignored_issues_28d_proj",
    "product_facts.performance_units_accepted_28d": "projects_data_outcomes.performance_units_accepted_28d",
    "product_facts.transactions_utilization_rate_avg": "projects_data_outcomes.transactions_utilization_rate_avg",
    "product_facts.org_active_traces": "organizations_events.org_active_traces",
    "product_facts.spans_utilization_rate_avg": "projects_data_outcomes.spans_utilization_rate_avg",
    "accounts_billingmetricusage_on_org.sum_quantity_28d": "projects_data_outcomes.sum_quantity_28d",
    "product_facts.first_spans_date_week": "organizations_feature_adoption_dates.first_spans_week",
    "product_facts.first_spans_date_date": "organizations_feature_adoption_dates.first_spans_date_date",
    "data_by_sdk.spans_28d_proj_sdkfamily": "sdk_base_events.spans_28d_proj_sdkfamily",
    "data_by_sdk.transactions_28d_proj_sdkfamily": "sdk_base_events.transactions_28d_proj_sdkfamily",
    "product_facts.profiles_accepted_28d": "projects_data_outcomes.profiles_accepted_28d",
    "product_facts.sum_errors_rate_limited": "organizations_data_outcomes.errors_rate_limited",
    "expansion_churn_scores.slug": "organizations.slug",
    "product_facts.daily_new_performance_issues_28d_org": "projects_issues.daily_new_performance_issues_28d_proj",
    "product_facts.sum_indexed_transactions_rate_limited": "organizations_data_outcomes.indexed_transactions_rate_limited",
    "product_facts.indexed_transactions_accepted_28d": "projects_data_outcomes.indexed_transactions_accepted_28d",
    "product_facts.sum_indexed_transactions_filtered": "projects_data_outcomes.indexed_transactions_filtered",
    "product_facts.sum_errors_filtered": "projects_data_outcomes.errors_filtered",
    "data_by_sdk.number_of_errors_28d": "sdk_base_events.errors_28d_proj_sdk",
    "data_by_sdk.number_of_transactions_28d": "sdk_base_events.transactions_28d_proj_sdk",
    "data_by_project.indexed_transactions_accepted_28d": "projects_data_outcomes.indexed_transactions_accepted_28d",
    "data_by_sdk.number_of_events_28d": "sdk_base_events.events_28d_proj_sdk",
    "product_facts_alerts_array.primary_alertrule_id_slack": "projects_metric_alerts.primary_alertrule_id_slack",
    "product_facts_alerts_array.primary_alertrule_id_email": "projects_metric_alerts.has_email_action",
    "product_facts_alerts_array.primary_alertrule_id_pagerduty": "projects_metric_alerts.primary_alertrule_id_pagerduty",
    "product_facts_alerts_array.primary_alertrule_id": "projects_metric_alerts.primary_alertrule_id",
    "product_facts_alerts_array.primary_alertrule_id_msteams": "projects_metric_alerts.primary_alertrule_id_msteams",
    "product_facts_alerts_array.primary_alertrule_id_sentryapp": "projects_metric_alerts.has_sentryapp_action",
    "product_facts_alerts_array.primary_alertrule_id_active": "projects_metric_alerts.primary_alertrule_id_active",
    "product_facts.github_stacktrace_linked_successes": "organizations_analytics_specific.github_stacktrace_linked",
    "product_facts.created_dashboard_count": "organizations_analytics_specific.created_dashboard_count",
    "product_facts.transaction_summary_visit_count": "projects_analytics_specific.performance_transaction_summary_visits",
    "product_facts.performance_landing_page_visit_count": "organizations_analytics_specific.performance_landing_page_visits",
    "product_facts.opened_discover_query_count": "projects_analytics_specific.opened_discover_query",
    "product_facts.viewed_dashboard_count": "organizations_analytics_specific.viewed_dashboard_count",
    "data_by_project.proj_codeowner_rule_count": "projects_base_table.proj_codeowner_rule_count",
    "product_facts_analytics_array.percent_of_users_visiting_discover_query": "projects_analytics_summary.percent_of_users_visiting_discover_query",
    "product_facts.avg_org_active_users_28d": "organizations_age_tracking.avg_org_active_users_28d",
    "data_by_sdk.number_of_events": "sdk_base_events.events",
    "product_facts.sum_transactions_rate_limited": "projects_data_outcomes.transactions_rate_limited",
    "product_facts.sum_transactions_accepted": "projects_data_outcomes.transactions_accepted",
    "product_facts.total_metric_alerts_generated": "projects_analytics_specific.generated_metric_alerts",
    "product_facts.total_issue_alerts_generated": "projects_analytics_specific.generated_issue_alerts",
    "issues_by_type_struct.daily_new_performance_issues_sum": "issues_org_type.daily_new_performance_issues_sum",
    "issues_by_type_struct.daily_resolved_performance_issues_sum": "issues_base_type.daily_resolved_performance_issues",
    "product_facts.sum_replays_rate_limited": "projects_data_outcomes.sum_replays_rate_limited",
    "product_facts_features_array._individual_features": "organizations_integrations__all_integration_features_array._individual_features",
    "product_facts_events.web": "organizations_events.web",
    "product_facts_events.server": "organizations_events.server",
    "product_facts_events.desktop": "organizations_events.desktop",
    "product_facts_events.mobile": "organizations_events.mobile",
    "product_facts.sum_errors_invalid_abuse": "projects_data_outcomes.errors_invalid_abuse",
    "product_facts.sum_transactions_filtered": "organizations_data_outcomes.transactions_filtered",
    "product_facts.sum_transactions_invalid_abuse": "projects_data_outcomes.transactions_invalid_abuse",
    "product_facts.discover_activity_count": "organizations_analytics_specific.discover_activity_28d_org",
    "data_by_sdk.sessions_crashed_28d": "sdk_base_events.sessions_crashed_28d_proj_sdk",
    "data_by_sdk.sessions_abnormal_sum": "sdk_base_events.sessions_abnormal",
    "data_by_sdk.total_sessions_28d": "sdk_base_events.total_sessions_28d_proj_sdk",
    "data_by_sdk.crash_free_sessions_28d": "sdk_base_events.crash_free_sessions_28d",
    "data_by_sdk.sessions_crashed_sum": "sdk_base_events.sessions_crashed",
    "data_by_sdk.crash_free_rate_percent": "sdk_base_events.crash_free_rate_percent",
    "data_by_sdk.crash_free_rate": "sdk_base_events.crash_free_rate_percent",
    "data_by_sdk.total_sessions_sum": "sdk_base_events.total_sessions",
    "product_facts.org_id_link_to_engagement_score": "organizations_feature_flags.org_id_link_to_engagement_score",
    "product_facts.org_id_link_to_project_health": "organizations_feature_flags.org_id_link_to_project_health",
    "product_facts.sum_attachments_accepted": "organizations_data_outcomes.attachments_accepted",
    "product_facts.sum_profiles_accepted": "organizations_data_outcomes.profiles_accepted",
    "product_facts.org_active_mobile": "organizations_feature_flags.org_active_mobile",
    "product_facts.alert_rules": "organizations_feature_flags.alert_rules",
    "product_facts.source_maps": "organizations_feature_flags.source_maps",
    "product_facts.release_tracking": "organizations_feature_flags.release_tracking",
    "product_facts.custom_tags": "organizations_feature_flags.custom_tags",
    "product_facts.transactions_client_side_sampling_rate_28d": "organizations_analytics_summary.transactions_client_side_sampling_rate_28d",
    "product_facts.seer_issue_fixes_accepted_sum": "organizations_seer.seer_issue_fixes_accepted_sum",
    "product_facts.seer_issue_scans_accepted_sum": "organizations_seer.seer_issue_scans_accepted_sum",
    "user_details.given_name": "user_details_for_analytics.given_name",
    "user_details.username": "user_details_for_analytics.username",
    "user_details.full_name": "user_details_for_analytics.full_name",
    "emerge_first_adoption_dates.first_size_analysis_date": "organizations_feature_adoption_dates.first_size_analysis_date",
    "metric_type_events.median_size_bytes": "metric_type_events.median_size_bytes",
},
("forecasts_v2", "subscriptions_v3"): {},
("product_facts", "product_usage_sdk"): {
    "accounts_billingmetricusage_on_org.outcome_readable": "accounts_billingmetricusage_on_org.outcome_readable",
    "accounts_billingmetricusage_on_org.sum_quantity_28d": "projects_data_outcomes.sum_quantity_28d",
    "billing_model.billing_model": "daily_arr_by_category.billing_model",
    "billing_model_billing_category.sum_churn_arr": "daily_arr_changes_category.sum_total_churn_arr",
    "billing_model_billing_category.sum_contraction_arr": "daily_arr_changes_category.sum_total_contraction_arr",
    "billing_model_billing_category.sum_expansion_arr": "daily_arr_changes_category.sum_total_expansion_arr",
    "billing_model_billing_category.sum_new_arr": "daily_arr_changes_category.sum_total_new_arr",
    "billing_model_billing_category.sum_reactivation_arr": "daily_arr_changes_category.sum_total_reactivation_arr",
    "daily_financial_data_billing_category_struct.change_in_ondemand_arr": "daily_arr_changes_category.ondemand_change_arr",
    "data_by_project.attachments_accepted_28d": "projects_data_outcomes.attachments_accepted_28d",
    "data_by_project.client_side_filters_used": "projects_data_outcomes.client_side_filters_used",
    "data_by_project.client_side_sampling_used": "projects_data_outcomes.client_side_sampling_used",
    "data_by_project.codemapping_enabled": "projects_configuration.codemapping_enabled_flag",
    "data_by_project.create_jira_ticket_issue_alert_count": "projects_alert_rules.count_of_alert_rules_to_create_ticket",
    "data_by_project.custom_tags_issue_alerts_count": "projects_alert_rules.count_of_alert_rules_with_custom_tags",
    "data_by_project.daily_ignored_issues_28d_proj": "projects_issues.daily_ignored_issues_28d_proj",
    "data_by_project.daily_new_issues_28d_proj": "projects_issues.daily_new_issues_28d_proj",
    "data_by_project.daily_resolved_issues_28d_proj": "projects_issues.daily_resolved_issues_28d_proj",
    "data_by_project.environment_based_metric_alerts_count": "projects_metric_alerts.environment_based_alert_rules_count",
    "data_by_project.error_count_issue_alerts_count": "projects_alert_rules.count_of_alerts_for_issue_based_event_count",
    "data_by_project.error_spike_metric_alerts_count": "projects_metric_alerts.error_spike_metric_alerts_count",
    "data_by_project.errors_accepted_28d": "projects_data_outcomes.errors_accepted_28d",
    "data_by_project.errors_over_quota_quarter_count": "projects_configuration.errors_over_quota_quarter_count",
    "data_by_project.events_accepted_28d": "projects_data_outcomes.events_accepted_28d",
    "data_by_project.has_environments_current_enabled": "projects_configuration.has_environments_current_flag",
    "data_by_project.indexed_transactions_accepted_28d": "projects_data_outcomes.indexed_transactions_accepted_28d",
    "data_by_project.messaging_integration_issue_alerts_count": "projects_alert_rules.count_of_messaging_integrations",
    "data_by_project.new_issue_alerts_count": "projects_alert_rules.count_of_alerts_for_new_issues",
    "data_by_project.ownership_rules": "projects_configuration.number_of_ownership_rules",
    "data_by_project.primary_sdk": "projects_base_table.primary_sdk",
    "data_by_project.profiles_accepted_28d": "projects_data_outcomes.profiles_accepted_28d",
    "data_by_project.proj_codeowner_rule_count": "projects_base_table.proj_codeowner_rule_count",
    "data_by_project.proj_errors_accepted": "projects_data_outcomes.errors_accepted",
    "data_by_project.proj_replays_accepted": "projects_data_outcomes.replays_accepted",
    "data_by_project.proj_spans_accepted": "projects_data_outcomes.daily_spans_accepted",
    "data_by_project.proj_team_member_count": "projects_team_assignments.team_members_count",
    "data_by_project.proj_trace_metric_items_accepted": "projects_data_outcomes.trace_metric_items_accepted",
    "data_by_project.project_count": "projects_data_outcomes.project_count",
    "data_by_project.project_first_event_date_date": "sentry_projects.first_event_date",
    "data_by_project.project_id": "product_facts_v2_base.project_id",
    "data_by_project.project_name": "sentry_projects.name",
    "data_by_project.project_platform": "sentry_project.platform",
    "data_by_project.regression_issue_alerts_count": "projects_alert_rules.count_of_alerts_for_regression",
    "data_by_project.releases_created_through_cli": "projects_releases.releases_created_through_cli",
    "data_by_project.releases_having_commits_associated": "projects_releases.releases_having_commits_associated",
    "data_by_project.replays_accepted_28d": "projects_data_outcomes.replays_accepted_28d",
    "data_by_project.replays_over_quota_quarter_count": "projects_configuration.replays_over_quota_quarter_count",
    "data_by_project.sdk_integrations_enabled": "projects_events.sdk_integrations_flag",
    "data_by_project.server_side_filters_used": "projects_configuration.server_side_filters_used",
    "data_by_project.single_event_issue_percent_28d_proj": "projects_base_table.single_event_issue_percent_28d_proj",
    "data_by_project.spend_allocation_enabled_flag": "projects_configuration.spend_allocation_enabled_flag",
    "data_by_project.spike_protection_disabled": "projects_configuration.spike_protection_disabled_flag",
    "data_by_project.team_notification_issue_alert_count": "projects_alert_rules.count_of_alert_rules_notifying_team",
    "data_by_project.transactional_data_metric_alerts_count": "projects_metric_alerts.transaction_based_alerts_count",
    "data_by_project.transactions_accepted_28d": "projects_data_outcomes.transactions_accepted_28d",
    "data_by_project.transactions_over_quota_quarter_count": "projects_configuration.transactions_over_quota_quarter_count",
    "data_by_sdk.Total_replays_28d": "sdk_base_events.replays_28d_proj_sdk",
    "data_by_sdk.crash_free_rate": "sdk_base_events.crash_free_rate_percent",
    "data_by_sdk.crash_free_rate_percent": "sdk_base_events.crash_free_rate_percent",
    "data_by_sdk.crash_free_sessions_28d": "sdk_base_events.crash_free_sessions_28d",
    "data_by_sdk.events_28d_proj_sdkfamily": "sdk_base_events.events_28d_proj_sdkfamily",
    "data_by_sdk.log_size_bytes_28d": "sdk_base_events.log_size_bytes_28d_proj_sdk",
    "data_by_sdk.log_size_bytes_28d_proj_sdkfamily": "sdk_base_events.log_size_bytes_28d_proj_sdkfamily",
    "data_by_sdk.mobile_replays_28d_proj_sdkfamily": "sdk_base_events.mobile_replays_28d_proj_sdkfamily",
    "data_by_sdk.number_of_errors_28d": "sdk_base_events.errors_28d_proj_sdk",
    "data_by_sdk.number_of_events": "sdk_base_events.events",
    "data_by_sdk.number_of_events_28d": "sdk_base_events.events_28d_proj_sdk",
    "data_by_sdk.number_of_mobile_replays_28d": "sdk_base_events.mobile_replays_28d_proj_sdk",
    "data_by_sdk.number_of_transactions_28d": "sdk_base_events.transactions_28d_proj_sdk",
    "data_by_sdk.pduration_backend_28d_sdk_family": "sdk_base_events.pduration_backend_28d_proj_sdkfamily",
    "data_by_sdk.pduration_frontend_28d_sdk_family": "sdk_base_events.pduration_frontend_28d_proj_sdkfamily",
    "data_by_sdk.replays_28d_proj_sdkfamily": "sdk_base_events.replays_28d_proj_sdkfamily",
    "data_by_sdk.sdk_family": "sdk_map_new.language_family",
    "data_by_sdk.sdk_integrations_string": "sdk_base_events.sdk_integrations_string",
    "data_by_sdk.sdk_name": "sdk_base_events.sdk_name",
    "data_by_sdk.sessions_abnormal_sum": "sdk_base_events.sessions_abnormal",
    "data_by_sdk.sessions_crash_free_sum": "sdk_base_events.sessions_crash_free_sum",
    "data_by_sdk.sessions_crashed_28d": "sdk_base_events.sessions_crashed_28d_proj_sdk",
    "data_by_sdk.sessions_crashed_sum": "sdk_base_events.sessions_crashed",
    "data_by_sdk.spans_28d_proj_sdkfamily": "sdk_base_events.spans_28d_proj_sdkfamily",
    "data_by_sdk.total_accepted_replay_count": "sdk_base_events.replays_28d_proj_sdk",
    "data_by_sdk.total_pduration__28d_sdk_family": "sdk_base_events.total_pduration__28d_sdk_family",
    "data_by_sdk.total_sessions_28d": "sdk_base_events.total_sessions_28d_proj_sdk",
    "data_by_sdk.total_sessions_sum": "sdk_base_events.total_sessions",
    "data_by_sdk.trace_metric_items_28d": "sdk_base_events.trace_metric_items_28d_proj_sdk",
    "data_by_sdk.trace_metric_size_bytes_28d": "sdk_base_events.trace_metric_size_bytes_28d_proj_sdk",
    "data_by_sdk.transactions_28d_proj_sdkfamily": "sdk_base_events.transactions_28d_proj_sdkfamily",
    "data_by_sdkversion.errors": "sdk_base_events.errors",
    "data_by_sdkversion.log_size_bytes": "sdk_base_events.log_size_bytes",
    "data_by_sdkversion.logs_origin": "sdk_base_events.logs_origin",
    "data_by_sdkversion.median_log_size_bytes": "sdk_base_events.median_log_size_bytes",
    "data_by_sdkversion.median_metric_size_bytes": "sdk_base_events.median_trace_metric_size_bytes",
    "data_by_sdkversion.number_of_events": "sdk_base_events.events",
    "data_by_sdkversion.profile_duration_backend": "sdk_base_events.profile_duration_backend",
    "data_by_sdkversion.profile_duration_frontend": "sdk_base_events.profile_duration_frontend",
    "data_by_sdkversion.profiles": "sdk_base_events.profiles",
    "data_by_sdkversion.sdk_version": "sdk_base_events.sdk_version",
    "data_by_sdkversion.sdk_version_crons_support_proj": "sdk_mapping_minversion.crons_support",
    "data_by_sdkversion.sdk_version_profiles_support_proj": "sdk_mapping_minversion.profile_support",
    "data_by_sdkversion.sdk_version_replays_support_proj": "sdk_mapping_minversion.replay_support",
    "data_by_sdkversion.sdk_version_transactions_support_proj": "sdk_mapping_minversion.transaction_support",
    "data_by_sdkversion.total_profile_duration_continuous": "sdk_base_events.profile_duration_backend",
    "data_by_sdkversion.trace_metric_items": "sdk_base_events.trace_metric_items",
    "data_by_sdkversion.trace_metric_size_bytes": "sdk_base_events.trace_metric_size_bytes",
    "data_by_sdkversion.transactions": "sdk_base_events.transactions",
    "data_by_sdkversion.uses_latest_sdk_version": "sdk_base_events.uses_latest_sdk_version",
    "issues_by_type_struct.daily_new_performance_issues_sum": "issues_org_type.daily_new_performance_issues_sum",
    "issues_by_type_struct.daily_resolved_performance_issues_sum": "issues_base_type.daily_resolved_performance_issues",
    "metric_type_events.median_attributes": "projects_data_outcomes.median_attributes",
    "metric_type_events.metric_items": "projects_data_outcomes.metrics_accepted",
    "organization_uptime_summary.org_dt_total_active_monitors": "organizations.org_dt_total_active_monitors",
    "product_facts.active_organizations_count": "organizations.active_organizations_count",
    "product_facts.alert_rules": "organizations_feature_flags.alert_rules",
    "product_facts.avg_org_active_users_28d": "organizations_age_tracking.avg_org_active_users_28d",
    "product_facts.combined_integration_features": "organizations_integrations.all_integration_features_string",
    "product_facts.created_dashboard_count": "organizations_analytics_specific.created_dashboard_count",
    "product_facts.crons_active_monitor_1d": "organizations_cron_monitoring.crons_active_monitor_1d",
    "product_facts.custom_tags": "organizations_feature_flags.custom_tags",
    "product_facts.daily_new_performance_issues_28d_org": "projects_issues.daily_new_performance_issues_28d_proj",
    "product_facts.discover_activity_count": "organizations_analytics_specific.discover_activity_28d_org",
    "product_facts.dt_date": "product_facts_v2_base.dt_date",
    "product_facts.dt_fiscal_quarter": "product_facts_v2_base.dt_fiscal_quarter",
    "product_facts.dt_month": "product_facts_v2_base.dt_month",
    "product_facts.dt_week": "product_facts_v2_base.dt_week",
    "product_facts.errors_accepted_28d": "projects_data_outcomes.errors_accepted_28d",
    "product_facts.errors_utilization_rate": "projects_data_outcomes.errors_utilization_rate",
    "product_facts.external_ticket_integration_flag": "organizations_integrations.external_ticket_integration_flag",
    "product_facts.first_continuous_profile_date_date": "organizations_feature_adoption_dates.first_continuous_profile_date",
    "product_facts.first_logs_date_date": "organizations_feature_adoption_dates.first_logs_date_date",
    "product_facts.first_logs_date_month": "organizations_feature_adoption_dates.first_logs_date_month",
    "product_facts.first_spans_date_date": "organizations_feature_adoption_dates.first_spans_date_date",
    "product_facts.first_spans_date_week": "organizations_feature_adoption_dates.first_spans_week",
    "product_facts.first_ui_profile_date_date": "organizations_feature_adoption_dates.first_ui_profile_date_date",
    "product_facts.front_end_profile_duration_accepted_sum": "projects_data_outcomes.frontend_profile_duration_accepted",
    "product_facts.frontend_profile_duration_accepted_28d": "projects_data_outcomes.frontend_profile_duration_accepted_28d",
    "product_facts.github_integration": "organizations_integrations.github_integration",
    "product_facts.github_stacktrace_linked_successes": "organizations_analytics_specific.github_stacktrace_linked",
    "product_facts.indexed_spans_accepted_28d": "projects_data_outcomes.indexed_spans_accepted_28d",
    "product_facts.indexed_transactions_accepted_28d": "projects_data_outcomes.indexed_transactions_accepted_28d",
    "product_facts.is_last_day_of_month": "product_facts_v2_base.is_last_day_of_month",
    "product_facts.is_last_day_of_week": "product_facts_v2_base.is_last_day_of_week",
    "product_facts.logs_accepted_28d": "projects_data_outcomes.logs_bytes_accepted_28d",
    "product_facts.logs_count_28d": "projects_data_outcomes.logs_items_accepted_28d",
    "product_facts.opened_discover_query_count": "projects_analytics_specific.opened_discover_query",
    "product_facts.org_active": "organizations.is_active",
    "product_facts.org_active_backend": "organizations_feature_flags.org_active_backend",
    "product_facts.org_active_frontend": "sdk_map_new.framework_frontend",
    "product_facts.org_active_mobile": "organizations_feature_flags.org_active_mobile",
    "product_facts.org_active_traces": "organizations_events.org_active_traces",
    "product_facts.org_active_users_28d": "organizations_active_users.org_active_users_28d",
    "product_facts.org_age": "organizations_age_tracking.org_age",
    "product_facts.org_ea_flag": "organizations_analytics_summary.org_ea_flag",
    "product_facts.org_id_link_to_engagement_score": "organizations_feature_flags.org_id_link_to_engagement_score",
    "product_facts.org_id_link_to_project_health": "organizations_feature_flags.org_id_link_to_project_health",
    "product_facts.organization_id": "product_facts_v2_base.organization_id",
    "product_facts.organization_name": "organizations_analytics_summary.organization_name",
    "product_facts.organization_slug": "organizations.slug",
    "product_facts.organizations_count": "product_facts_v2_base.count",
    "product_facts.performance_landing_page_visit_count": "organizations_analytics_specific.performance_landing_page_visits",
    "product_facts.performance_units_accepted": "projects_data_outcomes.performance_units_accepted",
    "product_facts.performance_units_accepted_28d": "projects_data_outcomes.performance_units_accepted_28d",
    "product_facts.profile_duration_accepted_28d": "organizations_data_outcomes.profile_duration_accepted_28d",
    "product_facts.profile_duration_accepted_sum": "projects_data_outcomes.profile_duration_accepted",
    "product_facts.profiles_accepted_28d": "projects_data_outcomes.profiles_accepted_28d",
    "product_facts.release_tracking": "organizations_feature_flags.release_tracking",
    "product_facts.replays_accepted_28d": "projects_data_outcomes.replays_accepted_28d",
    "product_facts.seer_issue_fixes_accepted_sum": "organizations_seer.seer_issue_fixes_accepted_sum",
    "product_facts.seer_issue_scans_accepted_sum": "organizations_seer.seer_issue_scans_accepted_sum",
    "product_facts.source_maps": "organizations_feature_flags.source_maps",
    "product_facts.spans_accepted_28d": "organizations_data_outcomes.spans_accepted_28d",
    "product_facts.spans_utilization_rate_avg": "projects_data_outcomes.spans_utilization_rate_avg",
    "product_facts.sso_provider": "organizations_sso_configuration.provider",
    "product_facts.sso_status": "organizations_sso_configuration.sso_status",
    "product_facts.sso_users_28d": "organizations_sso_configuration.num_users_last_28days_from_snapshot",
    "product_facts.sum_active_projects": "organizations_data_outcomes.org_active_projects",
    "product_facts.sum_attachments_accepted": "organizations_data_outcomes.attachments_accepted",
    "product_facts.sum_errors_accepted": "projects_data_outcomes.errors_accepted",
    "product_facts.sum_errors_filtered": "projects_data_outcomes.errors_filtered",
    "product_facts.sum_errors_invalid_abuse": "projects_data_outcomes.errors_invalid_abuse",
    "product_facts.sum_errors_rate_limited": "organizations_data_outcomes.errors_rate_limited",
    "product_facts.sum_indexed_transactions_filtered": "projects_data_outcomes.indexed_transactions_filtered",
    "product_facts.sum_indexed_transactions_rate_limited": "organizations_data_outcomes.indexed_transactions_rate_limited",
    "product_facts.sum_logs_accepted": "projects_data_outcomes.logs_bytes_accepted",
    "product_facts.sum_org_active_users_28d": "organizations.active_users_28d",
    "product_facts.sum_org_users_total": "organizations_active_users.org_users_total",
    "product_facts.sum_profiles_accepted": "organizations_data_outcomes.profiles_accepted",
    "product_facts.sum_replays_accepted": "projects_data_outcomes.replays_accepted",
    "product_facts.sum_replays_rate_limited": "projects_data_outcomes.sum_replays_rate_limited",
    "product_facts.sum_spans_accepted": "projects_data_outcomes.daily_spans_accepted",
    "product_facts.sum_transactions_accepted": "projects_data_outcomes.transactions_accepted",
    "product_facts.sum_transactions_filtered": "organizations_data_outcomes.transactions_filtered",
    "product_facts.sum_transactions_invalid_abuse": "projects_data_outcomes.transactions_invalid_abuse",
    "product_facts.sum_transactions_rate_limited": "projects_data_outcomes.transactions_rate_limited",
    "product_facts.total_issue_alerts_generated": "projects_analytics_specific.generated_issue_alerts",
    "product_facts.total_metric_alerts_generated": "projects_analytics_specific.generated_metric_alerts",
    "product_facts.total_profile_duration_accepted_28d": "projects_data_outcomes.profile_duration_accepted_28d",
    "product_facts.total_profile_duration_accepted_sum": "organizations_data_outcomes.profile_duration_accepted",
    "product_facts.trace_metric_items_accepted_28d": "organizations_data_outcomes.trace_metric_items_accepted_28d",
    "product_facts.trace_metric_items_accepted_sum": "projects_data_outcomes.trace_metric_items_accepted",
    "product_facts.transaction_summary_visit_count": "projects_analytics_specific.performance_transaction_summary_visits",
    "product_facts.transactions_accepted_28d": "projects_data_outcomes.transactions_accepted_28d",
    "product_facts.transactions_client_side_sampling_rate_28d": "organizations_analytics_summary.transactions_client_side_sampling_rate_28d",
    "product_facts.transactions_utilization_rate": "projects_data_outcomes.transactions_utilization_rate",
    "product_facts.transactions_utilization_rate_avg": "projects_data_outcomes.transactions_utilization_rate_avg",
    "product_facts.viewed_dashboard_count": "organizations_analytics_specific.viewed_dashboard_count",
    "product_facts_alerts_array.primary_alertrule_id": "projects_metric_alerts.primary_alertrule_id",
    "product_facts_alerts_array.primary_alertrule_id_active": "projects_metric_alerts.primary_alertrule_id_active",
    "product_facts_alerts_array.primary_alertrule_id_email": "projects_metric_alerts.has_email_action",
    "product_facts_alerts_array.primary_alertrule_id_msteams": "projects_metric_alerts.primary_alertrule_id_msteams",
    "product_facts_alerts_array.primary_alertrule_id_pagerduty": "projects_metric_alerts.primary_alertrule_id_pagerduty",
    "product_facts_alerts_array.primary_alertrule_id_sentryapp": "projects_metric_alerts.has_sentryapp_action",
    "product_facts_alerts_array.primary_alertrule_id_slack": "projects_metric_alerts.primary_alertrule_id_slack",
    "product_facts_analytics_array.percent_of_users_visiting_discover_query": "projects_analytics_summary.percent_of_users_visiting_discover_query",
    "product_facts_events.desktop": "organizations_events.desktop",
    "product_facts_events.event_type": "organizations_events.event_type",
    "product_facts_events.events_28d": "organizations_data_outcomes.events_accepted_28d",
    "product_facts_events.mobile": "organizations_events.mobile",
    "product_facts_events.number_of_events_sum": "organizations_events.number_of_events_sum",
    "product_facts_events.sdk_family": "organizations_events.sdk_family",
    "product_facts_events.sdk_name": "organizations_events.sdk_name",
    "product_facts_events.server": "organizations_events.server",
    "product_facts_events.web": "organizations_events.web",
    "product_facts_features_array._individual_features": "organizations_integrations__all_integration_features_array._individual_features",
    "product_facts_org_rca_feedback.changes_negative_feedback": "product_facts_org_rca_feedback.changes_negative_feedback",
    "product_facts_org_rca_feedback.rca_negative_feedback": "product_facts_org_rca_feedback.rca_negative_feedback",
    "product_facts_org_rca_feedback.rca_positive_feedback": "product_facts_org_rca_feedback.rca_positive_feedback",
    "product_facts_org_rca_feedback.solution_positive_feedback": "product_facts_org_rca_feedback.rca_positive_feedback",
    "sdk_base_events.replays_28d_proj_sdk": "sdk_base_events.replays_28d_proj_sdk",
    "sdk_integrations_array.individual_sdk_integrations": "sdk_org_events.individual_sdk_integrations",
    "sdk_mapping_minversion_project.crons_support": "sdk_org_events.crons_support",
    "sdk_mapping_minversion_project.profile_support": "sdk_org_events.profile_support",
    "sdk_mapping_minversion_project.replay_support": "sdk_org_events.replay_support",
    "sdk_mapping_minversion_project.transaction_support": "sdk_org_events.transaction_support",
    "subscriptions_v3.total_new_arr": "daily_arr_changes_org.sum_total_new_arr",
    "trial_view.trial_start_month": "organizations_trial_view.trial_start_month",
    "user_details.full_name": "user_details.full_name",
    "user_details.username": "user_details_for_analytics.username",
    "user_details_for_analytics.email": "user_details_for_analytics.email",
    "user_details_for_analytics.full_name": "user_details_for_analytics.full_name",
    "user_details_for_analytics.is_staff": "user_details_for_analytics.is_staff",
    "user_details_for_analytics.is_superuser": "user_details_for_analytics.is_superuser",
},
("subscriptions_v3", "subscriptions_v3"): {
    "billing_model.sum_total_new_arr":                                    "daily_arr_changes_org.sum_total_new_arr",
    "billing_model.sum_total_churn_arr":                                  "daily_arr_changes_org.sum_total_churn_arr",
    "billing_model.sum_total_reactivation_arr":                           "daily_arr_changes_org.sum_total_reactivation_arr",
    "billing_model.sum_total_expansion_arr":                              "daily_arr_changes_org.sum_total_expansion_arr",
    "billing_model.sum_total_contraction_arr":                            "daily_arr_changes_org.sum_total_contraction_arr",
    "billing_model_billing_category.sum_new_arr":                         "daily_arr_changes_category.sum_total_new_arr",
    "billing_model_billing_category.sum_churn_arr":                       "daily_arr_changes_category.sum_total_churn_arr",
    "billing_model_billing_category.sum_reactivation_arr":                "daily_arr_changes_category.sum_total_reactivation_arr",
    "billing_model_billing_category.sum_expansion_arr":                   "daily_arr_changes_category.sum_total_expansion_arr",
    "billing_model_billing_category.sum_contraction_arr":                 "daily_arr_changes_category.sum_total_contraction_arr",
    "daily_financial_data.total_change_in_ondemand_arr":                  "daily_arr_changes_org.ondemand_change_arr",
    "daily_financial_data.is_net_churn":                                  "daily_arr_changes_org.is_net_churn",
    "daily_financial_data.total_churn_arr":                               "daily_arr_changes_org.total_churn_arr",
    "daily_financial_data.total_contraction_arr":                         "daily_arr_changes_org.total_contraction_arr",
    "daily_financial_data.total_expansion_arr":                           "daily_arr_changes_org.total_expansion_arr",
    "daily_financial_data.total_new_arr":                                 "daily_arr_changes_org.total_new_arr",
    "daily_financial_data.total_reactivation_arr":                        "daily_arr_changes_org.total_reactivation_arr",
    "daily_financial_data.total_churn_payg_arr":                          "daily_arr_changes_org.ondemand_churn_arr",
    "daily_financial_data.total_contraction_payg_arr":                    "daily_arr_changes_org.ondemand_contraction_arr",
    "daily_financial_data.total_expansion_payg_arr":                      "daily_arr_changes_org.ondemand_expansion_arr",
    "daily_financial_data.total_new_payg_arr":                            "daily_arr_changes_org.ondemand_new_arr",
    "daily_financial_data.total_reactivation_payg_arr":                   "daily_arr_changes_org.ondemand_reactivation_arr",
    "daily_financial_data_billing_category_struct.change_in_ondemand_arr": "daily_arr_changes_category.ondemand_change_arr",
    "daily_financial_data_billing_category_struct.is_net_churn":          "daily_arr_changes_category.is_net_churn",
    "daily_financial_data_billing_category_struct.churn_arr":             "daily_arr_changes_category.reserved_churn_arr",
    "daily_financial_data_billing_category_struct.contraction_arr":       "daily_arr_changes_category.reserved_contraction_arr",
    "daily_financial_data_billing_category_struct.expansion_arr":         "daily_arr_changes_category.reserved_expansion_arr",
    "daily_financial_data_billing_category_struct.new_arr":               "daily_arr_changes_category.reserved_new_arr",
    "daily_financial_data_billing_category_struct.reactivation_arr":      "daily_arr_changes_category.reserved_reactivation_arr",
    "daily_financial_data_billing_category_struct.churn_payg_arr":        "daily_arr_changes_category.ondemand_churn_arr",
    "daily_financial_data_billing_category_struct.contraction_payg_arr":  "daily_arr_changes_category.ondemand_contraction_arr",
    "daily_financial_data_billing_category_struct.expansion_payg_arr":    "daily_arr_changes_category.ondemand_expansion_arr",
    "daily_financial_data_billing_category_struct.new_payg_arr":          "daily_arr_changes_category.ondemand_new_arr",
    "daily_financial_data_billing_category_struct.reactivation_payg_arr": "daily_arr_changes_category.ondemand_reactivation_arr",
},
}

FIELD_MAP = {}
for _old in OLD_EXPLORE:
    for _new in (NEW_EXPLORE, NEW_EXPLORE_2):
        FIELD_MAP.update(FIELD_MAPS.get((_old, _new), {}))

